# Generated by Django 4.2.1 on 2023-05-21 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='Desc',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='Firstname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='Mobile',
        ),
        migrations.AddField(
            model_name='contact',
            name='Lastname',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
    ]
