# Generated by Django 4.2.1 on 2023-05-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_date_contact_date_rename_desc_contact_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Desc',
            field=models.TextField(blank=True, max_length=122, null=True),
        ),
    ]
