# Generated by Django 4.2.1 on 2023-05-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Firstname',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Lastname',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
